version: "3.8"

services:

  mysql:
    image: mysql:8
    container_name: banking-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2131
      MYSQL_DATABASE: bankingdb
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p2131"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: banking-app
    ports:
      - "9090:9090"

    depends_on:
      mysql:
        condition: service_healthy

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bankingdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 2131

volumes:
  mysql-data: